name: Building
on: [push]
jobs:
  building:
    runs-on: ubuntu-latest
    steps:
      - name: Check GH repository
        uses: actions/checkout@v3
      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9.11"
      - name: Install Poetry Action
        uses: snok/install-poetry@v1
        with:
          version: 1.1.15
      - name: Install dependences with Poetry
        run: poetry install
      - name: Testing
        run: poetry run pytest
      - name: Build Mi Paquete
        run: poetry build
      - name: GH Release
        if: startsWith(github.ref, 'refs/tags/v*.')
        uses: softprops/action-gh-release@v1
        with:
          files: |
            ${{ github.workspace }}/dist/*
            LICENSE
            README.md
